############# Croatian navigation ##############
# main menu    
[[main]]
name = "Za skipera"
URL = "/"
weight = 1
  
[[main]]
name = "Za operatera"
URL = "operator/"
weight = 2

[[main]]
weight = 3
name = "O nama"
hasChildren = true
  [[main]]
  parent = "O nama"
  name = "Društvo"
  URL = "about/"
  weight = 1
  
  [[main]]
  parent = "O nama"
  name = "Tim"
  URL = "team/"
  weight = 2

#Footer menu

[[footer]]
name = "O nama"
URL = "about/"

[[footer]]
name = "Kontakt"
URL = "contact/"

[[footer]]
name = "Impressum"
URL = "pricy-policy/"

[[footer]]
name = "zaštita podataka"
URL = "pricy-policy/"