############# English navigation ##############
# main menu    
[[main]]
name = "Für Skipper"
URL = "/"
weight = 1
  
[[main]]
name = "Für Betreiber"
URL = "operator/"
weight = 2

[[main]]
weight = 3
name = "Über Uns"
hasChildren = true

  [[main]]
  parent = "Über Uns"
  name = "Unternehmen"
  URL = "about/"
  weight = 1

  [[main]]
  parent = "Über Uns"
  name = "Team"
  URL = "team/"
  weight = 2

#Footer menu

[[footer]]
name = "Über Uns"
URL = "about/"

[[footer]]
name = "Kontakt"
URL = "contact/"

[[footer]]
name = "Impressum"
URL = "#"

[[footer]]
name = "Datenschutzerklärung"
URL = "#"